"""Generate the documentation changelog page from the root ``CHANGELOG.md``.

``CHANGELOG.md`` lives at the repository root, where GitHub and PyPI look for
it, but Zensical only serves files under ``docs_dir``. Rather than move the file
or symlink it, this writes a committed page under ``docs/``.

It is a *generate-then-build* step, like ``scripts/ci_policy.py`` is a
*decide-then-run* one: the generated page is committed, so ``zensical build``
stays hermetic and reproducible. ``--check`` re-renders and compares without
writing, which is what ``tests/infrastructure/test_changelog.py`` asserts, so a
changelog edit that forgets to sync fails CI instead of silently shipping a
stale page.

Usage::

    python scripts/sync_changelog.py            # write docs/changelog.md
    python scripts/sync_changelog.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "CHANGELOG.md"
TARGET = ROOT / "docs" / "changelog.md"

MARKER = (
    "<!-- Generated by scripts/sync_changelog.py from CHANGELOG.md at the "
    "repository root. Do not edit by hand. -->"
)


def render(source_text: str) -> str:
    """Render the docs page from the root changelog's text.

    The root file already opens with an ``# Changelog`` H1, which is the page
    title Zensical wants, so the body passes through unchanged. Only the
    generated marker is inserted, directly after the H1 so it does not land
    between the title and the first paragraph in the rendered page.
    """
    lines = source_text.rstrip("\n").split("\n")
    if not lines or not lines[0].startswith("# "):
        raise ValueError(f"{SOURCE.name} must start with an H1 heading")
    out = [lines[0], "", MARKER, *lines[1:]]
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify docs/changelog.md is up to date instead of writing it",
    )
    args = parser.parse_args()

    expected = render(SOURCE.read_text(encoding="utf-8"))

    if not args.check:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(expected, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return 0

    actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if actual == expected:
        print(f"{TARGET.relative_to(ROOT)} is up to date")
        return 0

    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{TARGET.relative_to(ROOT)} (committed)",
        tofile=f"{TARGET.relative_to(ROOT)} (expected)",
    )
    sys.stdout.writelines(diff)
    print(
        f"\n{TARGET.relative_to(ROOT)} is out of date. Run: python scripts/sync_changelog.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
